var kick1 = new Tone.Player("./Kick/Kick001.wav").toDestination();
var kick2 = new Tone.Player("./Kick/Kick002.wav").toDestination();
var kick3 = new Tone.Player("./Kick/Kick003.wav").toDestination();
var kick4 = new Tone.Player("./Kick/Kick004.wav").toDestination();
var kick5 = new Tone.Player("./Kick/Kick005.wav").toDestination();
var kick6 = new Tone.Player("./Kick/Kick006.wav").toDestination();
var kick7 = new Tone.Player("./Kick/Kick007.wav").toDestination();
var kick8 = new Tone.Player("./Kick/Kick008.wav").toDestination();
var kick9 = new Tone.Player("./Kick/Kick009.wav").toDestination();

document.getElementById("kick1").onclick = () => kick1.start();
document.getElementById("kick2").onclick = () => kick2.start();
document.getElementById("kick3").onclick = () => kick3.start();
document.getElementById("kick4").onclick = () => kick4.start();
document.getElementById("kick5").onclick = () => kick5.start();
document.getElementById("kick6").onclick = () => kick6.start();
document.getElementById("kick7").onclick = () => kick7.start();
document.getElementById("kick8").onclick = () => kick8.start();
document.getElementById("kick9").onclick = () => kick9.start();
